### ISSUE TITLE
Undefined variable with vim 7.4

### ISSUE THREAD

**Issue by infinite-ops** [ojroques/vim-scrollstatus#1]
With vim 7.4 it complains:
```
Error detected while processing /home/user/.vim/plugged/vim-scrollstatus/plugin/scrollstatus.vim:
line   10:
E121: Undefined variable: v:true
E15: Invalid expression: v:true
Press ENTER or type command to continue
```

If I comment line 10 out of scrollstatus.vim the complaint goes away and the plugin works as expected
```
" let g:loaded_scrollstatus = v:true
```
Using vim 8.2 it does not complain at all and works as expected out the box.

Either way love the plugin! I'm using it with lightline

**Comment by ojroques** [comment]
Thanks for the feedback! I changed the variable from `v:true` to `1`.

**Comment by infinite-ops** [comment]
perfect! thank you for the quick turnaround!
