### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by nashio** [ojroques/vim-scrollstatus#2]
Does this work with neovim?
Wasn't able to make it work

**Comment by ojroques** [comment]
I'm also using neovim (v0.4.3) so yes it should work. Here's a minimal config to make it work, assuming you're using vim-plug and vim-airline:

```vim
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'ojroques/vim-scrollstatus'
call plug#end()

let g:airline_section_x = '%{ScrollStatus()} '
```
