### ISSUE TITLE
E117: Unknown function: airline#section#create

### ISSUE THREAD

**Issue by jmmendivil** [ojroques/vim-scrollstatus#4]
Great script, thanks.

I have vim-airline installed and I tried to use the example config from the README but I get an error:

`E117: Unknown function: airline#section#create`

VIM - Vi IMproved 8.2
macOS 10.15.7

**Comment by ojroques** [comment]
Seems like the `create` function was not loaded. Can you share the vim config you're using?

**Comment by jmmendivil** [comment]
Sure, here is my current _vimrc:

https://gist.github.com/jmmendivil/442885317e98ef4e0fbe57e67028ce27#file-_vimrc-L36

**Comment by ojroques** [comment]
Mmh at first sight I don't see anything wrong in your config. It's probably related to Vundle but I'm not familiar with how it works. You should probably open an issue in vim-airline since its not directly related to the plugin though.
