### ISSUE TITLE
vim-scrollstatus looks like abnormal

### ISSUE THREAD

**Issue by ghost** [ojroques/vim-scrollstatus#5]
## You can see the next picture,vim-scrollstatus not like demo gif. What can I do?
---
![image](https://user-images.githubusercontent.com/83897793/125231389-3cdb0a00-e30d-11eb-9ac1-711410000734.png)

![image](https://user-images.githubusercontent.com/83897793/125231712-d99da780-e30d-11eb-810d-e78bfeb38104.png)

### My vim-scrollstatus configuration
```
let g:lightline = {
  \ 'active': {
  \   'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding', 'filetype', 'charvaluehex']]
  \ },
  \ 'component_function': {'percent': 'ScrollStatus'},
  \ }
let g:scrollstatus_size = 15
```
My neovim version is 0.5 dev.

Help me please

**Comment by ojroques** [comment]
Hello!

The way the scrollbar looks depends on your font. I guess you have two solutions here, either you change your font or you change the characters used to display the scrollbar. You can do that using these two options:

```vim
let g:scrollstatus_symbol_track = '-' let g:scrollstatus_symbol_bar = '|'
```

Check Unicode characters for more options also.

**Comment by ghost** [comment]
ohhh,Thank you so very much! You are right, different unicodes can display the different scrollbar. I have found a character I like, really really thank you :) 👍🏻

**Comment by ghost** [comment]
I will close this issue, I hope this issue can help other people!
